apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: devops-calculator
          image: 958006149889.dkr.ecr.ap-south-1.amazonaws.com/calculator:v1
          ports:
            - containerPort: 5000
