apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: devops-calculator
          image: mukilansentha/calculator-app-project:v2
          ports:
            - containerPort: 5000
